### ISSUE TITLE
Adding Fibonacci Heap

### ISSUE THREAD

**Issue by admin-d** [raviMaurya12/DSandAlgo#10]
## **`Fibonacci Heap`** -

**Adding Fibonacci Heap DataStructure to this repository** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Self Check 

- Ask for an issue assignment and wait to get assigned to it before making Pull Request.
- `Clean Code` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by admin-d** [comment]
Can I work on this? @raviMaurya12

**Comment by raviMaurya12** [comment]
Sure

**Comment by aditya-gupta-i** [comment]
Merged #11
