### ISSUE TITLE
Adding Disjoint-Set-Union

### ISSUE THREAD

**Issue by admin-d** [raviMaurya12/DSandAlgo#12]
## **`Disjoint-Set-Union`** -

**Adding C++ implementation of DSU data-structure** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Self Check 

- Ask for an issue assignment and wait to get assigned to it before making Pull Request.
- `Clean Code` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by admin-d** [comment]
Can I work on this?

**Comment by aditya-gupta-i** [comment]
Merged #13
