### ISSUE TITLE
Adding Dijkstra Algorithm

### ISSUE THREAD

**Issue by developer-nobita** [raviMaurya12/DSandAlgo#15]
## **`Add Dijkstra Algorithm`** -

**Dijkstra Algorithm's C++ code will be added to this repo** -

### Type of Issue - 
- [x] Adding New Code

### Self Check 

- Ask for an issue assignment and wait to get assigned to it before making Pull Request.
- `Clean Code` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by developer-nobita** [comment]
Can I work on this? @raviMaurya12

**Comment by PradeepKumarDwivedi** [comment]
Can you please assign it to me? @R0ckGithub

**Comment by aditya-gupta-i** [comment]
PR #16 

Mention your issue number next time in the PR
